### ISSUE TITLE
Your instance's APl did notreturn your user data.

### ISSUE THREAD

**Issue by qiancsff** [Xyphyn/photon#374] opened 2024-07-25 07:41 UTC
Your instance's APl did notreturn your user data.
![22](https://github.com/user-attachments/assets/ea411d9a-c7ce-4c23-b6e9-0f3b2ea8f1d8)

**Comment by sevonj** [comment] 2024-07-25 11:38
I think it'd be a good idea to use the provided bug report template and add more details.

**Comment by Xyphyn** [comment] 2024-07-25 17:30
Dupe of #361

**Closed by Xyphyn** 2024-07-25 17:30 UTC
Labels: bug
