### ISSUE TITLE
Blank screen for new Lemmy instance

### ISSUE THREAD

**Issue by Showfom** [Xyphyn/photon#140] opened 2023-09-03 14:31 UTC
**Describe the bug**
It's just a blank screen without any content shows on a new Lemmy instance [R.NF](https://r.nf/)

**To Reproduce** (if applicable)
1. Go to https://phtn.app/post/r.nf/1
2. See error

**Expected behavior**

**Screenshots**

**Versions**
- Browser: Firefox
- Photon version: 0.5.1
  - check in the bottom of the main menu.

**Comment by Xyphyn** [comment] 2023-09-03 15:34
Photon has feature parity, but is not a drop in replacement. The blank screen is caused by it failing to fetch posts.

You must create the site via lemmy-ui first before you can use Photon.

Photon does not support password resets or email verification either, so I'd recommend keeping Photon as a separate UI for now.

**Comment by Showfom** [comment] 2023-09-04 00:10
@Xyphyn 

Yes the instance with lemmy-ui works fine https://r.nf/

But not working with photon, and there's no log from docker.

**Comment by Showfom** [comment] 2023-09-04 00:22
Seems photon is not working with latest Lemmy 0.18.4-beta.8

For example

https://lemmy.miichelle.moe/post/1
https://photon.lemmy.world/post/lemmy.miichelle.moe/1

https://r.nf/post/1
https://photon.lemmy.world/post/r.nf/1

Both instances are running with Lemmy 0.18.4-beta.8

**Comment by Xyphyn** [comment] 2023-09-04 02:57
![image](https://github.com/Xyphyn/photon/assets/80978739/434f50f3-f468-4920-a6e4-149912d5bf0f)

weird

**Comment by Xyphyn** [comment] 2023-09-04 03:04
Should be fixed in v1.2.3

**Comment by Xyphyn** [comment] 2023-09-04 04:05
Isn't fixed.

**Comment by MusicSongs-Org** [comment] 2023-09-04 21:47
photon has a hard-coded 'Z' it adds to all the published date fields of Lemmy, that's been changed in the API response to already have the 'Z'.

**Comment by Xyphyn** [comment] 2023-09-04 21:49
> Regarding 'invalid date' parsing, photon has a hard-coded 'Z' it adds to all the date fields of Lemmy, that's been changed in the Lemmy API response to already have the 'Z'.

omfg why do they keep changing this

**Comment by Xyphyn** [comment] 2023-09-04 21:52
That shouldn't crash though

**Comment by Xyphyn** [comment] 2023-09-04 22:01
Haven't completely fixed the issue on this particular instance, but did add compatibility for the new version and some error handling just in case it fails.

**Closed by Xyphyn** 2023-09-04 22:01 UTC
Labels: bug

**Comment by drphero** [comment] 2023-10-04 15:31
For anyone still having trouble with this, make sure to completely clear the cache and cookies for phtn.app and it should load properly.
