### ISSUE TITLE
Title does not update sometimes

### ISSUE THREAD

**Issue by blox814123** [Xyphyn/photon#321] opened 2024-05-26 08:16 UTC
When clicking "home", it keeps the post title.

**Comment by Xyphyn** [comment] 2024-05-26 20:36
This same issue is present on https://reddit.com, funnily enough. I'll try fixing it soon

**Comment by blox814123** [comment] 2024-05-26 20:58
You are right, haha.

**Comment by Xyphyn** [comment] 2024-09-05 00:39
Dupe of #287

**Closed by Xyphyn** 2024-09-05 00:39 UTC
Labels: bug
