### ISSUE TITLE
White text on white background with dark theme

### ISSUE THREAD

**Issue by KAMiKAZOW** [Xyphyn/photon#120] opened 2023-08-24 08:22 UTC
![image](https://github.com/Xyphyn/photon/assets/3259076/9f5b1ecb-d429-482b-9d55-af45fd22b375)

**Comment by Xyphyn** [comment] 2023-08-24 21:49
That is a browser native menu, so this is probably an issue with your browser.

**Comment by KAMiKAZOW** [comment] 2023-08-25 10:12
> That is a browser native menu, so this is probably an issue with your browser.

No, it's not. Everywhere else it works just fine. It's just Photon that does that. Browser is Firefox.

For example Mastodon:

![image](https://github.com/Xyphyn/photon/assets/3259076/cd6fd91d-fe5f-4777-82ac-b6bfc223bb42)

>  closed this as completed

Don't close issues as "completed" you don't actually complete, please. It's makes testing and reporting bugs tiring.

**Comment by Xyphyn** [comment] 2023-08-25 14:59
How the heck am I supposed to fix a browser native menu? I can't even test it since it works on my browser.

**Comment by Xyphyn** [comment] 2023-08-25 22:42
![image](https://github.com/Xyphyn/photon/assets/80978739/0c7db10c-11ad-4863-a8de-fb073651169b)

Can't reproduce on Librewolf, Brave, or Firefox.

**Comment by Xyphyn** [comment] 2023-09-07 01:09
I think it's fixed with the new components.

**Closed by Xyphyn** 2023-09-07 01:09 UTC
Labels: bug
